STR_MODES = {1: "NORMAL", 
             2: "HARD"}
MODE_NORMAL = 1
MODE_HARD = 2
MODES = {'1': MODE_NORMAL,
         '2': MODE_HARD}

PLAYER_LIVES = 2
POINTS_FOR_FIGHT = 1
POINTS_FOR_KILLING = 1
MAX_RECORDS_NUMBER = 5
HARD_MODE_MULTIPLIER = 2

SCORE_FILE = 'scores.txt'

PAPER = 'Paper'
STONE = 'Stone'
SCISSORS = 'Scissors'

WIN = 1
DRAW = 0
LOSE = -1

ALLOWED_ATTACKS = {
    '1': PAPER,
    '2': STONE,
    '3': SCISSORS
}

ATTACK_PAIRS_OUTCOME = {
    (PAPER, PAPER): DRAW,
    (PAPER, STONE): WIN,
    (PAPER, SCISSORS): LOSE,
    (STONE, PAPER): LOSE,
    (STONE, STONE): DRAW,
    (STONE, SCISSORS): WIN,
    (SCISSORS, PAPER): WIN,
    (SCISSORS, STONE): LOSE,
    (SCISSORS, SCISSORS): DRAW
}

START = 'Start game'
SCORE = 'Show scores'
EXIT = 'Exit game'

MENU_OPTIONS = {
    '1': START,
    '2': SCORE,
    '3': EXIT
}

# Emoji
 
ICONS = {
    'Paper': '\U0001F4C4',
    'Stone': '\U0001F9F1',
    'Scissors': '\U00002702'
}

THINKING_FACE = "\U0001F914"
WEARY_FACE = "\U0001F629"
ANGRY_FACE = "\U0001F620"
GRINNING_FACE = "\U0001F600"
SKULL = "\U0001F480"
CROSSED_SWORDS = "\U00002694"
SHIELD = "\U0001F6E1"